
name = "supaflare-worker"
main = 'index.js'
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-10"
kv_namespaces = [
  { binding = "SUPAFLARE", id = "3c3571bdbdd84b20acc7db9df14a838d" },
]
